services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: funvedar
      POSTGRES_PASSWORD: funvedar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-app:
    build:
      context: . # Build context is the current directory (my-go-postgres-app)
      dockerfile: Dockerfile # Specifies the Dockerfile to use
    container_name: my-go-app
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      - db # Ensure the 'db' service starts before 'go-app'
    environment:
      # Environment variables for your Go application to connect to PostgreSQL
      # Note: Use 'db' as the hostname, not 'localhost', because 'db' is the service name in Docker Compose
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: funvedar
      DATABASE_PASSWORD: funvedar
      DATABASE_NAME: testing
    restart: on-failure # Restart if the application crashes

volumes:
  postgres_data: